### ISSUE TITLE
CriticalCSS Generation - RequestError: connect ECONNREFUSED

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-vite#24]
I'm having trouble getting CriticalCSS generated on a Nitro2 setup. When I run Vite inside my Nitro container (i.e. `nitro ssh`), I can successfully run `build` and generate my CSS, JS, manifest, and favicons. I can also get HMR working when running `dev`.

But I get an error when generating my CriticalCSS. It seems like it's some type of connection issue, so I've tried, rather blindly and unsuccessfully, to modify the Critical-related settings in both `vite.config.js` and `config/vite.php`. 

Here's the error I get.

```
Generating critical CSS from http://mylittlepony.test/offices to offices/index_critical.min.css
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1642638594328,
    socket: 1642638594329,
    lookup: 1642638594329,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1642638594330,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 2
    }
  }
}
```

Any guidance on what the culprit is would be much appreciated! I'm figuring I can get this working on a non-Nitro2 setup. But I can't seem to give up on Nitro2! 

Running the latest version of Craft and Vite plugin. Also using the following settings:

In `vite.config.js`
```
import legacy from '@vitejs/plugin-legacy'
import ViteRestart from 'vite-plugin-restart';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import critical from 'rollup-plugin-critical';
import { ViteFaviconsPlugin } from "vite-plugin-favicon2";
import path from 'path';

export default ({ command }) => ({
  base: command === 'serve' ? '' : '/dist/',
  build: {
    emptyOutDir: true,
    manifest: true,
    outDir: './web/dist/',
    rollupOptions: {
      input: {
        app: './src/js/app.js',
      }
    },
  },
  plugins: [
    legacy({
      targets: ['defaults', 'not IE 11']
    }),
    nodeResolve({
      moduleDirectories: [
        path.resolve('./node_modules'),
      ],
    }),
    ViteRestart({
      reload: [
          './templates/**/*',
      ],
    }),
    ViteFaviconsPlugin({
      logo: "./src/img/favicon-src.png",
      inject: false,
      outputPath: 'favicons',
    }),
    critical({
      criticalUrl: 'http://mylittlepony.test/',
      criticalBase: './web/dist/criticalcss',
      criticalPages: [
        { uri: '', template: 'index' },
        { uri: 'offices', template: 'offices/index' },
      ],
      criticalConfig: {
      }
    }),
  ],
  publicDir: './src/public',
  resolve: {
    alias: {
      '@': '/src'
    }
  },
  server: {
    host: '0.0.0.0',
	 https: false,
  }
});
```

In `config/vite.php`
```
<?php
use craft\helpers\App;
return [

    'useDevServer' => App::env('ENVIRONMENT') === 'dev',
    'manifestPath' => '@webroot/dist/manifest.json',
    'devServerPublic' => 'http://mylittlepony.test:3000/',
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',
    'errorEntry' => '/src/js/app.js',
    'cacheKeySuffix' => '',
    'devServerInternal' => 'http://localhost:3000/',
    'checkDevServer' => true,
    'includeReactRefreshShim' => false,
    'criticalPath' => '@webroot/dist/criticalcss',
    'criticalSuffix' =>'_critical.min.css',
];
```

**Comment by khalwat** [comment]
If you're expecting to generate the critical CSS from the running dev server, probably you will need to find out the internal network name that Nitro uses for its node container.

I don't use Nitro, so unfortunately I'm not sure how to assist further.
